version: '3.8'

services:
  # ----------------------------------------------------
  # SERVICIO DE BACKEND (PYTHON/SCAPY)
  # ----------------------------------------------------
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    # La capacidad NET_ADMIN es crucial para que Scapy pueda
    # capturar paquetes sin necesidad de usar 'sudo' en el host.
    cap_add:
      - NET_ADMIN
    # Usar el modo de red del host para darle a Scapy acceso directo 
    # a las interfaces de red del sistema.
    network_mode: "host" 
    # Mapear el puerto 5000 (si network_mode es 'host' es opcional, 
    # pero ayuda a documentar). Si usas "host", el puerto 5000 del 
    # contenedor es el 5000 del host.
    ports:
      - "5000:5000"
    restart: unless-stopped
    # Montar el código fuente para desarrollo (opcional, pero útil)
    # volumes:
    #   - ./python-back:/app/python-back
    
  # ----------------------------------------------------
  # SERVICIO DE FRONTEND (REACT/VITE - PRODUCCIÓN)
  # ----------------------------------------------------
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      # Exponer el frontend en el puerto 5173 para acceso externo
      - "5173:80"
    # Asegúrate de que el frontend sepa dónde encontrar el backend
    environment:
      # OJO: Mantenemos la IP 127.0.0.1 porque el backend usa 
      # network_mode: "host", lo que hace que 127.0.0.1 dentro del 
      # contenedor de frontend apunte al host de Docker.
      - API_BASE_URL=http://127.0.0.1:5000/api
    depends_on:
      - backend